name: Run mini_lattice notebook

on:
  push:
    paths:
      - 'notebooks/mini_lattice.ipynb'
      - '.github/workflows/run_notebook.yml'
      - 'src/**'          # kod değişirse de yeniden çalışsın
  workflow_dispatch:      # elle tetikleme düğmesi

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install CI deps
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-ci.txt

    - name: Run notebook with papermill
      run: |
        papermill notebooks/mini_lattice.ipynb executed.ipynb --cwd .

    - name: Convert executed notebook to HTML (optional)
      run: |
        jupyter nbconvert executed.ipynb --to html

    - name: Upload lattice result artifact
      uses: actions/upload-artifact@v4
      with:
        name: lattice-results
        path: |
          executed.ipynb
          executed.html
          out/mini_lattice_results.npz
